### ISSUE TITLE
Problem with installing uncoder on macos via zsh shell

### ISSUE THREAD

**Issue by venom861** [UncoderIO/Uncoder_IO#84]
Hi I am having problems with installation, running the docker compose cmd, i keep running into this issue of  > [uncoder-os 8/8] RUN yarn build:                                                       
0.169 yarn run v1.22.19                                                                   
0.192 $ cross-env NODE_ENV=production webpack                                             
28.81 assets by status 10.8 MiB [cached] 473 assets                                       
28.81 Entrypoint main = style.css main.bundle.js 469 auxiliary assets                     
28.81 orphan modules 2.91 MiB (javascript) 38.5 KiB (runtime) [orphan] 1152 modules
28.81 runtime modules 1.44 KiB 8 modules
28.81 built modules 2.53 MiB (javascript) 1.04 MiB (css/mini-extract) [built] 605 modules
28.81 
28.81 ERROR in /app/tsconfig.json
28.81 /app/tsconfig.json
28.81 [tsl] ERROR
28.81       TS2688: Cannot find type definition file for 'mime'.
28.81   The file is in the program because:
28.81     Entry point for implicit type library 'mime'
28.81 ts-loader-default_04bb2ec108ef140d
28.81 
28.81 webpack 5.91.0 compiled with 1 error in 28058 ms
28.96 error Command failed with exit code 1.
28.96 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Would you be able to resolve this?

**Comment by Mzapeka** [comment]
Fixed
