### ISSUE TITLE
Index field is not filled in elasticksearch_detection_rule

### ISSUE THREAD

**Issue by HosseinAkhoundi** [UncoderIO/Uncoder_IO#91]
In the mapping section, the index field is mapped according to the roll type, but the index field is not filled after translation.
but in socprime index field is filled
![Screenshot from 2024-04-08 14-13-24](https://github.com/UncoderIO/Uncoder_IO/assets/88624115/94132113-2d57-447d-86bd-62c7b7dfba61)
![image](https://github.com/UncoderIO/Uncoder_IO/assets/88624115/5c5f1f5c-e25f-46a0-a551-8f60b7ad7142)

**Comment by Ginger-Headed** [comment]
Thanks for raising this. Took into work.
