### ISSUE TITLE
Convert from specific SIEM to Sigma

### ISSUE THREAD

**Issue by Radu1999** [UncoderIO/Uncoder_IO#92]
Hi, is there any roadmap to include conversion to Sigma from SIEM languages?

**Comment by enceladus3** [comment]
That would be amazing!

**Comment by Ginger-Headed** [comment]
Hi,

Support for direct translation from SIEM-native languages into Sigma is not part of Uncoder IO roadmap. However, you have two options to do that right now:

1. You can use Uncoder AI where the Enterprise subscription plan includes translations from SIEM-native queries/rules into Sigma and other SIEM-native queries/rules.

2. You can convert a simple SIEM-native query (without functions) into a Sigma rule right now using [Roota](https://github.com/UncoderIO/RootA/blob/main/README.md#minimal-roota-rule-example). You can find the list of supported languages [here](https://github.com/UncoderIO/RootA/blob/main/RootA_Specification.md#language).
